### ISSUE TITLE
Crash when using custom player view

### ISSUE THREAD

**Issue by clackmac** [mhergon/AVPlayerViewController-Subtitles#11]
Hey! First of all, thank you for the extension, it is really simple and adds a lot of value.

This is more of an improvement than an issue actually, but happens when you are using a custom view for the player controller that the extension may crash depending on your implementation.

One common scenario on this is when you try to keep playing videos while in background and you pick one specific solution of the two provided by Apple [here](https://developer.apple.com/library/content/qa/qa1668/_index.html) 

In this scenarios, the extension may crash since it uses the `contentOverlayView` in order to add the `subtitleLabel`. If the `contentOverlayView` is nil, the app will crash trying to figure out the superview when creating constraints with the visual format specified.

Based on this, I changed the following

```
    fileprivate func addSubtitleLabel() {
        
        guard let _ = subtitleLabel else {
            
           // ... label setup
            contentOverlayView?.addSubview(subtitleLabel!)
            
            // ... continue constraints
    }
```

with something a little bit more defensive like:

```
    fileprivate func addSubtitleLabel() {
        
        guard let _ = subtitleLabel else {
            
           // ... label setup
           if contentOverlayView != nil {
                contentOverlayView?.addSubview(subtitleLabel!)
            } else {
                view.addSubview(subtitleLabel!)
            }            

            // ... continue constraints
    }
```

Hope this helps

**Comment by mhergon** [comment]
Hi,

Thanks for the fix, but this solution has a tiny problem:
![simulator screen shot 4 nov 2016 20 37 49](https://cloud.githubusercontent.com/assets/621373/20019922/e00a2212-a2ce-11e6-9a39-7c784311399f.png)

Subtitles are over the controls and this is a bad solution. Do you have an example usage with type of crash?

Thanks!

**Comment by clackmac** [comment]
Hey, yeah, I know... but the idea was to provide a quick fix to avoid crashes.

Regarding the example, I do, and it is based on the link I shared earlier. But I cannot share the code since its under a corporate policy.
