### ISSUE TITLE
func parseSubRip hava bug

### ISSUE THREAD

**Issue by g001613001** [mhergon/AVPlayerViewController-Subtitles#13]
I found the func parseSubRip
 let regexStr = "(?m)(^[0-9]+)([\\s\\S]*?)(?=\n\n)"
            let regex = try NSRegularExpression(pattern: regexStr, options: .caseInsensitive)
            let matches = regex.matches(in: payload, options: NSRegularExpression.MatchingOptions(rawValue: 0), range: NSMakeRange(0, payload.characters.count))

the  matches will lost last lines text

defaul srt have 6 lines 

but only match 5 lines

how to fix this bug?

**Comment by mhergon** [comment]
Hi,

Do you any example code/project for testing?

**Comment by g001613001** [comment]
Hi, 

I use your sample code AVPlayerViewController-Subtitles-master\Example

and it has a file "trailer_720p.srt".

this srt file has 6 lines.

but at "fileprivate func parseSubRip(_ payload: String)", i'm print matches.count

only print count 5 , lose the last 1 line.

i think is these code has bug:
let regex = try NSRegularExpression(pattern: regexStr, options: .caseInsensitive) 
let matches = regex.matches(in: payload, options: NSRegularExpression.MatchingOptions(rawValue: 0), range: NSMakeRange(0, payload.characters.count))

but, i can't fix this bug, so want to ask you, how to fix this bug.

thank you :)

attached is the sample code.

**Comment by g001613001** [comment]
this link is sample code for you:
[https://drive.google.com/open?id=0B7aDowXaoXIjeGhCOTE3UDdERXM](url)

**Comment by mhergon** [comment]
Fixed at v1.1.1
Sorry for delay
