### ISSUE TITLE
Objective-C Project used

### ISSUE THREAD

**Issue by appsyscode** [mhergon/AVPlayerViewController-Subtitles#14]
Objective-C can be imported and used in the project?

**Comment by mhergon** [comment]
Yes, no problem. See:
https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html

**Comment by appsyscode** [comment]
Ok.
This code is to call you?

      // Video file
        let videoFile = Bundle.main.path(forResource: "trailer_720p", ofType: "mov")
        
        // Subtitle file
        let subtitleFile = Bundle.main.path(forResource: "trailer_720p", ofType: "srt")
        let subtitleURL = URL(fileURLWithPath: subtitleFile!)
        
        // Movie player
        let moviePlayer = AVPlayerViewController()
        moviePlayer.player = AVPlayer(url: URL(fileURLWithPath: videoFile!))
        present(moviePlayer, animated: true, completion: nil)
        
        // Add subtitles
        moviePlayer.addSubtitles().open(file: subtitleURL)
        moviePlayer.addSubtitles().open(file: subtitleURL, encoding: String.Encoding.utf8)
        
        // Change text properties
        moviePlayer.subtitleLabel?.textColor = UIColor.red
        
        // Play
        moviePlayer.player?.play()

Objective-C?

**Comment by mhergon** [comment]
No, this code is the Swift version, but use in the Objective-C project is similar.

**Comment by appsyscode** [comment]
It is not I realize that it must be.I do not know how to.
I can not find the right solution...

**Comment by mhergon** [comment]
Uops! Sorry, this library is only for Swift
You can use the other similar library https://github.com/mhergon/MPMoviePlayerController-Subtitles
