### ISSUE TITLE
WebVTT subtitles

### ISSUE THREAD

**Issue by MohgaNabil** [mhergon/AVPlayerViewController-Subtitles#15]
Hi ,
just wondering if you guys support WEBVTT subtitles as I have several videos with VTT subtitles (see attachments ) but they won't show up. 

Appreciate your help :)

[sample_video_subtitles.vtt.zip](https://github.com/mhergon/AVPlayerViewController-Subtitles/files/769493/sample_video_subtitles.vtt.zip)

**Comment by mhergon** [comment]
Hi,

At present only SRT files are supported. You can use a WEBVTT to SRT converter.
Thanks!

**Comment by a-radwan** [comment]
Any new for VTT format?

**Comment by mhergon** [comment]
I'm working on a new version, but no ETA.
Sorry for delay.
