### ISSUE TITLE
Remote subtitle

### ISSUE THREAD

**Issue by leminhtuan2015** [mhergon/AVPlayerViewController-Subtitles#18]
Please help!!!

I dont want to download subtitle file to bundle and I want to get subtitle file from server (https://...)

Please help me with other way 

Thank sir!!!

```
let subtitleFile = Bundle.main.path(forResource: "1", ofType: "srt")
subtitleURL = URL(fileURLWithPath: subtitleFile!)
parser = Subtitles(file: subtitleURL!, encoding: .utf8)
```

**Comment by mhergon** [comment]
Hi,

Download subtitle with `NSURLSession`, `Alamofire` or similar to `Documents` folder and show from here.

**Comment by leminhtuan2015** [comment]
@mhergon Thank sir so much!!!!
