### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by nguyenhaidang** [mhergon/AVPlayerViewController-Subtitles#2]
- Your lib crash with let contents = try! String(contentsOfURL: filePath, encoding: encoding) please check this. Thank you
- You can make it richer with https://github.com/MuscleRumble/THLabel/tree/master/THLabel :)

**Comment by mhergon** [comment]
Hi @nguyenhaidang 

Can you send me an example with crash?
I tried the example and runs smoothly...

Thanks!
