### ISSUE TITLE
subtitleLabel.backgroundColor layout problem

### ISSUE THREAD

**Issue by Alexookah** [mhergon/AVPlayerViewController-Subtitles#21]
`
// Change text properties

moviePlayer.subtitleLabel?.textColor = UIColor.red
moviePlayer.subtitleLabel?.backgroundColor = UIColor.black
`

when using backgroundColor there is some problem when the subtitle is not active.
Any idea why this is happening?

![simulator screen shot 30 jun 2017 00 39 31](https://user-images.githubusercontent.com/9624843/27711727-b478c50e-5d2c-11e7-80e9-e8a57bb330d4.png)
![simulator screen shot 30 jun 2017 00 39 38](https://user-images.githubusercontent.com/9624843/27711731-b8350720-5d2c-11e7-9723-ce926215f5c3.png)

**Comment by Alexookah** [comment]
created a pull request to fix this issue

**Comment by mhergon** [comment]
Thanks @Alexookah ! 
Sorry for delay

**Comment by mhergon** [comment]
New version available with the fix, thanks @Alexookah
