### ISSUE TITLE
Does not parse the tags in the WEBVTT files

### ISSUE THREAD

**Issue by Nikita989** [mhergon/AVPlayerViewController-Subtitles#22]
Below is my WEBVTT file:
![screen shot 2017-07-24 at 6 34 28 pm](https://user-images.githubusercontent.com/22230651/28524771-7e41cfd6-709f-11e7-9f83-a7567291e31f.png)

 The  "c" tag used here is displayed as a string. Does it not implicitly parse the tags?

**Comment by mhergon** [comment]
WEBVTT and tags aren't supported for now. 
Sorry!
