### ISSUE TITLE
add NSDictionary subtitles support

### ISSUE THREAD

**Issue by Alexookah** [mhergon/AVPlayerViewController-Subtitles#24]
I am using this library to get the captions from youtube url while parsing the XML caption youtube provides. 
Creating a NSdictionary and using the NSDictionary in the library.

Should i make a pull request for this to be able to use a NSDictionary ?

**Comment by mhergon** [comment]
Feel free to make PR. I will check and test and evaluate if add to library.

Thanks

**Comment by Alexookah** [comment]
created a pull request. check it out.
