### ISSUE TITLE
iOS 11 - Subtitle position

### ISSUE THREAD

**Issue by furkanhatipoglu** [mhergon/AVPlayerViewController-Subtitles#26]
Hi, thank you for this awesome library. On iOS 11, subtitle position which is top-left corner is wrong. Could you please fix it?

**Comment by mhergon** [comment]
Can you provide a screenshot with the wrong position?
Thanks!

**Comment by furkanhatipoglu** [comment]
![img_0106](https://user-images.githubusercontent.com/24944616/29670521-88903992-88ef-11e7-9d74-40ef4e233102.PNG)
![img_0108](https://user-images.githubusercontent.com/24944616/29670522-88cba8d8-88ef-11e7-8988-14e370f492ed.PNG)

Hi, it looks like this

**Comment by oleghnidets** [comment]
Hi all,

I submitted the issue http://www.openradar.me/6468254622 to Apple some time ago (also I submitted at http://bugreport.apple.com/). Looks like `contentOverlayView` doesn't work as expected. I expected it is fixed in final iOS 11 release. But it still doesn't work.

**Comment by Alexookah** [comment]
http://www.openradar.me/6468254622
apple responded and someone else.
does this mean that the issue can be resolved by some workaround?

**Comment by oleghnidets** [comment]
@Alexookah Yees, it fixed the problem for me.

**Comment by Alexookah** [comment]
in ios 11.2 this issue is fixed. you can close this issue now

**Comment by mhergon** [comment]
@Alexookah perfect, thanks!
