### ISSUE TITLE
Support subtitles & cc on/off from the default AVPlayerViewController button

### ISSUE THREAD

**Issue by MihaiPantiru** [mhergon/AVPlayerViewController-Subtitles#28]
Would be great to have support for on/off subtitles & cc from the default AVPlayerViewController UI. 

I'll give a try to implement it, hope is possbile.

**Comment by mhergon** [comment]
I'm gonna find out if it's possible.
Thanks for the idea!

**Comment by mhergon** [comment]
This is not possible right now
