### ISSUE TITLE
Problem in iOS 11.0 and 11.1

### ISSUE THREAD

**Issue by Cris-Burlamaqui** [mhergon/AVPlayerViewController-Subtitles#29]
I'm facing a problem with the iOS 11.0 and 11.1. In both cases the system totally avoid the subtitleLabel constraints, it's like none of them were been implemented.
Have you guys ever faced this issue?

**Comment by Cris-Burlamaqui** [comment]
In these both versions there are a bug in the contentOverlayView size and here is a solution given by Apple:

playerViewController.view.setNeedsLayout() 
playerViewController.view.layoutIfNeeded() playerViewController.contentOverlayView?.translatesAutoresizingMaskIntoConstraints = true

**Comment by mhergon** [comment]
iOS Bug
