### ISSUE TITLE
Initializing Subtitles needs modification

### ISSUE THREAD

**Issue by rajdhakate** [mhergon/AVPlayerViewController-Subtitles#37]
Might change Subtitles init method and use a do try catch block. My app crashed when contents of file for URL path was unreadable.

`
        do {
            // Get string
            let string = try String(contentsOf: filePath, encoding: encoding)
            // Parse string
            parsedPayload = Subtitles.parseSubRip(string)
        }
        catch {
            print(error)
        }
        `

**Comment by mhergon** [comment]
Check contents before pass to Subtitles init.
You must make sure it exists before you use it
