### ISSUE TITLE
Subtitles/Captions not working in fullscreen mode

### ISSUE THREAD

**Issue by Jalpesh009** [mhergon/AVPlayerViewController-Subtitles#39]
I am not sure which settings i have to do for displaying captions in fullscreen mode.

Subtitles/Captions are working fine in normal play. But it not displaying in fullscreen(picture-in-picture) mode.

What am i missing here?

**Comment by mhergon** [comment]
I'm trying multiple options, settings and others on AVPlayerViewController and seems that is not supported on PiP.
I add the subtitles in a layer called "contentOverlayView" but when I send the video to the PiP it is not being displayed and it doesn't seem to have a solution.
