### ISSUE TITLE
Not all tags are parsed correctly.

### ISSUE THREAD

**Issue by mourke** [mhergon/AVPlayerViewController-Subtitles#4]
I was watching star wars and there were `<i>` tags that showed up (presuming they should be parsed as italics) and in despicable me there is `<font>` tags with color attributes that arent parsed either. Attached despicable me srt
[minions-yify-70900.zip](https://github.com/mhergon/AVPlayerViewController-Subtitles/files/253610/minions-yify-70900.zip)

**Comment by mhergon** [comment]
Hi,

Tags are not officially supported by the SubRip format. Perhaps in the future I will implement the tags.

Thank you!
