### ISSUE TITLE
Doesn't show last minutes

### ISSUE THREAD

**Issue by ShaneenDhahd** [mhergon/AVPlayerViewController-Subtitles#42]
The library doesn't show subtitles at the last minute
I tried more than .srt and more than movie
I noticed that the last minute doesn't appear

**Comment by mhergon** [comment]
Hi,

Can you give example files to test it?

Thanks!

**Comment by ShaneenDhahd** [comment]
I don't think I can give u files
it just the normal implementation 
but whenever the subtitles reaches the last minute it doesn't show them

**Comment by mhergon** [comment]
Hi,

I tried multiple files and works fine.
Please, give me an example file to try.

**Comment by HevenHoo** [comment]
Hi mhergon,
I have encountered the same issue with some srt files, following srt file is a sample file.
https://drive.google.com/file/d/1d9kmpLmfrb1hfQoywNNDPhezdzSKDLPQ/view.

The parseSubRip func, can only get the subtitles index to 1158 01:36:08,513 --> 01:36:10,878, the index 1159~1170 are ignored.

**Comment by HevenHoo** [comment]
> Hi,
> 
> I tried multiple files and works fine. Please, give me an example file to try.

Hi mhergon,
I have encountered the same issue with some srt files, following srt file is a sample file.
https://drive.google.com/file/d/1d9kmpLmfrb1hfQoywNNDPhezdzSKDLPQ/view.

The parseSubRip func, can only get the subtitles index to 1158 01:36:08,513 --> 01:36:10,878, the index 1159~1170 are ignored.

**Comment by ShaneenDhahd** [comment]
The 

> > Hi,
> > I tried multiple files and works fine. Please, give me an example file to try.
> 
> Hi mhergon, I have encountered the same issue with some srt files, following srt file is a sample file. https://drive.google.com/file/d/1d9kmpLmfrb1hfQoywNNDPhezdzSKDLPQ/view.
> 
> The parseSubRip func, can only get the subtitles index to 1158 01:36:08,513 --> 01:36:10,878, the index 1159~1170 are ignored.

To fix it just change the encoding from utf8 to 16

**Comment by HevenHoo** [comment]
ShaneenDhahd, the contents will be garbled after using utf16, thanks for your reply.

**Comment by ShaneenDhahd** [comment]
That was the fix for me cuz the content was arabic

**Comment by HevenHoo** [comment]
I resolved the issue by changing the "payload.count" to "payload.utf16.count" in regex.matches.
