### ISSUE TITLE
scanner deprecated since iOS 13

### ISSUE THREAD

**Issue by rkorat1** [mhergon/AVPlayerViewController-Subtitles#43]
'scanDouble' was deprecated in iOS 13
scanString(_:into:)

```
  scanner.scanDouble(&h)
   scanner.scanString(":", into: nil)
   scanner.scanDouble(&m)
   scanner.scanString(":", into: nil)
   scanner.scanDouble(&s)
   scanner.scanString(",", into: nil)
     scanner.scanDouble(&c)
```

fixing this to doesn't show subtitles

**Comment by mhergon** [comment]
Fixed on v1.3.2
Since Cocoapods isn't working right now, use code from tag "v1.3.2" or master branch via SPM

Thanks!
